### ISSUE TITLE
Possible con: You can not use half of your disk space

### ISSUE THREAD

**Issue by ceremcem** [mehlbox/buttersync#2]
With this approach, you will not be able to use half of your disk space because there is an obvious need to dump entire snapshot in a temporary file, which will take as much as current disk space usage.

Maybe you should point that in your Readme.

**Comment by mehlbox** [comment]
This would be the worst case if you had all your data in just one subvolume. If you had multiple subvolumes you could do them one by one and only need the amount of free space each subvolume takes. I will also implement a function to be able to store the temporary file on a usb drive.
Either way. I will point out the need for free space.

**Comment by ceremcem** [comment]
Thinking again, this worst case is only true if you are sending the very first snapshot. Because the rest has only the difference data. So sending 800 GiB would take 800 GiB of temporary data, yes, but second snapshot might take only 1 GiB or a few MiB of data. 

So pointing this situation is up to you actually.
